[package]
name = "Test-Area"
version = "0.1.0"
edition = "2021"

[dependencies]
io = "0.0.2"
eframe = { version = "0.29.1", features = ["glow"] }
winapi = { version = "0.3", features = ["windef", "winuser"] }
